"""Prompt candidate and token metrics schemas."""

from enum import Enum
from typing import List
from pydantic import BaseModel, Field


class CandidateStrategy(str, Enum):
    """Different optimization strategies to generate candidate prompts."""
    CONCISE = "concise"             # Minimalist, high-compression, zero-fluff directives
    STRUCTURED = "structured"       # Hierarchical Markdown: Role, Objective, Rules, Output Schema
    OPERATIONAL = "operational"     # Clarity-first, explicit edge-case guardrails, disambiguated


class TokenMetrics(BaseModel):
    """Deterministic token and size measurements."""
    token_count: int = Field(description="Deterministic token count using tokenizer")
    char_count: int = Field(description="Character count")
    word_count: int = Field(description="Word count")
    token_delta: int = Field(default=0, description="Tokens saved compared to original (original - candidate)")
    reduction_percentage: float = Field(default=0.0, description="Percentage of tokens reduced")


class PromptCandidate(BaseModel):
    """An individual candidate prompt generated by the optimizer."""
    id: str = Field(description="Unique candidate identifier, e.g. cand_concise")
    strategy: CandidateStrategy = Field(description="The architectural strategy employed")
    prompt_text: str = Field(description="The fully formulated candidate prompt")
    tokens: TokenMetrics = Field(description="Deterministic token measurements")
    rationale: str = Field(description="Why this specific structure and phrasing was chosen")
    preserved_hard_requirements: List[str] = Field(
        default_factory=list,
        description="IDs or names of hard requirements validated as present in this candidate"
    )
    changes_summary: List[str] = Field(
        default_factory=list,
        description="Key transformations applied in this candidate"
    )
